# Generated by Django 5.0 on 2023-12-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('Aluguel', 'Aluguel'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Empréstimos', 'Empréstimos'), ('Entretenimento', 'Entretenimento'), ('Outros', 'Outros'), ('Salário', 'Salário')], max_length=100),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('despesa', 'Despesa'), ('receita', 'Receita')], max_length=7),
        ),
    ]
