# Generated by Django 5.0 on 2023-12-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucai', '0002_alter_transacao_data_alter_transacao_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('Salário', 'Salário'), ('Aluguel', 'Aluguel'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Empréstimos', 'Empréstimos'), ('Entretenimento', 'Entretenimento'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
