# Generated by Django 5.0 on 2023-12-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucai', '0003_alter_transacao_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='descricao',
            field=models.CharField(choices=[('Salário', 'Salário'), ('Contas', 'Contas em geral'), ('Aluguel', 'Aluguel'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Empréstimos', 'Empréstimos'), ('Entretenimento', 'Entretenimento'), ('Outros', 'Outros')], max_length=100),
        ),
    ]
